[queries.py:312]	WARNING: No applicable predicate found in filter=''. Will assume '!= None'.
[queries.py:312]	WARNING: No applicable predicate found in filter=''. Will assume '!= None'.
Traceback (most recent call last):
  File "/home/greole/.local/bin/obr", line 8, in <module>
    sys.exit(main())
  File "/home/greole/data/code/OBR/src/obr/cli.py", line 959, in main
    cli(obj={})
  File "/home/greole/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/greole/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/greole/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/greole/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/greole/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/greole/.local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/greole/data/code/OBR/src/obr/cli.py", line 545, in status
    df = df.set_index(sort_by).sort_index().reset_index()
  File "/home/greole/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/greole/.local/lib/python3.9/site-packages/pandas/core/frame.py", line 6012, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of [''] are in the columns"
